version: 1.0

environments:
    coder:
        files:
            - name: "project files"
              enabled: false
              include:
                  - "./composer.json"
                  - "./.editorconfig"
                  - "./src/**/*.(php|ts|js)"
              instructions: |
                  These are all project files. You can edit them as you like.
