<?php

namespace Lack\Kindergarden\Chat;

enum ChatMessageRoleEnum
{

    /**
     * The System Pompt (by default the first prompt)
     */
    case SYSTEM;

    /**
     * The Assistant Message (generated by the assistant)
     */
    case ASSISTANT;

    /**
     * The User Message (supplied by the user)
     */
    case USER;

}
